import { getBotName } from '../../lib/botname.js';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';

export default {
    name: 'toword',
    alias: ['todocx', 'txt2docx', 'text2word', 'makedocx'],
    description: 'Convert text to a Word (.docx) document',
    category: 'utility',

    async execute(sock, m, args, PREFIX) {
        const chatId = m.key.remoteJid;

        const contextInfo = m.message?.extendedTextMessage?.contextInfo;
        const quotedText  = contextInfo?.quotedMessage?.conversation
                         || contextInfo?.quotedMessage?.extendedTextMessage?.text;

        const inputText = args.join(' ').trim() || quotedText?.trim();

        if (!inputText) {
            return sock.sendMessage(chatId, {
                text: `╭⊷『 📝 TEXT TO WORD 』\n│\n` +
                      `├⊷ *Usage:*\n` +
                      `├⊷ ${PREFIX}toword <your text here>\n` +
                      `│   — OR —\n` +
                      `├⊷ Reply to a text message with ${PREFIX}toword\n` +
                      `│\n` +
                      `├⊷ *Aliases:*\n` +
                      `├⊷ ${PREFIX}todocx\n` +
                      `├⊷ ${PREFIX}text2word\n` +
                      `│\n` +
                      `├⊷ *Example:*\n` +
                      `└⊷ ${PREFIX}toword Hello, this is my document!\n\n` +
                      `╰⊷ *${getBotName()} Utility* 🐾`
            }, { quoted: m });
        }

        await sock.sendMessage(chatId, { react: { text: '⏳', key: m.key } });

        try {
            const paragraphs = inputText.split(/\n+/).map(line => line.trim()).filter(Boolean);

            const doc = new Document({
                sections: [{
                    properties: {},
                    children: [
                        new Paragraph({
                            text: `Generated by ${getBotName()}`,
                            heading: HeadingLevel.HEADING_1,
                            alignment: AlignmentType.CENTER
                        }),
                        new Paragraph({ text: '' }),
                        ...paragraphs.map(line =>
                            new Paragraph({
                                children: [
                                    new TextRun({
                                        text: line,
                                        size: 24,
                                        font: 'Calibri'
                                    })
                                ],
                                spacing: { after: 120 }
                            })
                        ),
                        new Paragraph({ text: '' }),
                        new Paragraph({
                            children: [
                                new TextRun({
                                    text: `Created on ${new Date().toUTCString()}`,
                                    size: 18,
                                    color: '888888',
                                    italics: true
                                })
                            ],
                            alignment: AlignmentType.CENTER
                        })
                    ]
                }]
            });

            const buffer   = await Packer.toBuffer(doc);
            const wordCount = inputText.split(/\s+/).filter(Boolean).length;
            const charCount = inputText.length;

            await sock.sendMessage(chatId, { react: { text: '✅', key: m.key } });
            await sock.sendMessage(chatId, {
                document: buffer,
                mimetype: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                fileName: `${getBotName()}_${Date.now()}.docx`,
                caption: `╭⊷『 📝 WORD DOC READY 』\n│\n` +
                         `├⊷ *Words:* ${wordCount}\n` +
                         `├⊷ *Chars:* ${charCount}\n` +
                         `├⊷ *Size:* ${(buffer.length / 1024).toFixed(1)} KB\n` +
                         `╰⊷ *${getBotName()} Utility* 🐾`
            }, { quoted: m });

        } catch (err) {
            await sock.sendMessage(chatId, { react: { text: '❌', key: m.key } });
            await sock.sendMessage(chatId, {
                text: `╭⊷『 📝 TEXT TO WORD 』\n│\n` +
                      `├⊷ *Error:* ${err.message}\n` +
                      `└⊷ Please try again\n\n` +
                      `╰⊷ *${getBotName()} Utility* 🐾`
            }, { quoted: m });
        }
    }
};
